# basic options, I can say whatever
title: Air Corp

author: Air Corp1

email: shwn1544@gmail.com

description: New Bnb

Year: 2020

twitter_username: jekyll11

Search: true

#URL VARIABLES

url:

base url:

source code:

github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
